sudo: required
language: node_js
node_js:
    - 10.16.0
services:
    - docker

before_install:
    - docker build -t joewardcp/react-test -f ./client/Dockerfile.dev ./client
script: 
    - docker run -e CI=true joewardcp/react-test npm run test -- --coverage

after_success:
    - docker build -t joewardcp/multi-client ./client
    - docker build -t joewardcp/multi-nginx ./nginx
    - docker build -t joewardcp/multi-server ./server
    - docker build -t joewardcp/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_ID" --password-stdin

    - docker push joewardcp/multi-client
    - docker push joewardcp/multi-nginx
    - docker push joewardcp/multi-server
    - docker push joewardcp/multi-worker
